### ISSUE TITLE
Empty FASTA files but no error message

### ISSUE THREAD

**Issue by simone-says** [nextgenusfs/gfftk#2]
I have ~11 GFF files out of 70 that produce empty *.faa (FASTA) files using 'gfftk convert' but no error message is printed. There is nothing special about them, I manually inspected them and I don't see a difference between the ones that are working. Is there a formatting requirement I'm missing?

**Comment by hyphaltip** [comment]
and you are sure there are protein coding genes annotated for those particular GFF + genome files?

**Comment by simone-says** [comment]
Yes, here's an example of one: 
```
GWHAAFD00000008	4253	4377	CDS	.	+	BGI	CDS	0	ID=CDS;Parent=ENSPG16957;Parent_Accession=GWHTAAFD002532;Protein_Accession=GWHPAAFD002532;
GWHAAFD00000008	4253	5241	ENSPG16957	.	+	BGI	mRNA	.	ID=ENSPG16957;Accession=GWHTAAFD002532;Parent=ENSPG16957.gene;Parent_Accession=GWHGAAFD002532;
GWHAAFD00000008	4253	5241	ENSPG16957.gene	.	+	BGI	gene	.	ID=ENSPG16957.gene;Accession=GWHGAAFD002532;
GWHAAFD00000008	4797	5057	CDS	.	+	BGI	CDS	2	ID=CDS;Parent=ENSPG16957;Parent_Accession=GWHTAAFD002532;Protein_Accession=GWHPAAFD002532;
GWHAAFD00000008	5169	5241	CDS	.	+	BGI	CDS	0	ID=CDS;Parent=ENSPG16957;Parent_Accession=GWHTAAFD002532;Protein_Accession=GWHPAAFD002532;
GWHAAFD00000008	6000	6242	CDS	.	+	BGI	CDS	0	ID=CDS;Parent=ENSPG16958;Parent_Accession=GWHTAAFD002533;Protein_Accession=GWHPAAFD002533;
GWHAAFD00000008	6000	6604	ENSPG16958	.	+	BGI	mRNA	.	ID=ENSPG16958;Accession=GWHTAAFD002533;Parent=ENSPG16958.gene;Parent_Accession=GWHGAAFD002533;
GWHAAFD00000008	6000	6604	ENSPG16958.gene	.	+	BGI	gene	.	ID=ENSPG16958.gene;Accession=GWHGAAFD002533;
GWHAAFD00000008	6333	6604	CDS	.	+	BGI	CDS	1	ID=CDS;Parent=ENSPG16958;Parent_Accession=GWHTAAFD002533;Protein_Accession=GWHPAAFD002533;
GWHAAFD00000019	2445	2880	CDS	.	+	BGI	CDS	0	ID=CDS;Parent=ENSPG01343;Parent_Accession=GWHTAAFD003259;Protein_Accession=GWHPAAFD003259;
GWHAAFD00000019	2445	2880	ENSPG01343	.	+	BGI	mRNA	.	ID=ENSPG01343;Accession=GWHTAAFD003259;Parent=ENSPG01343.gene;Parent_Accession=GWHGAAFD003259;
GWHAAFD00000019	2445	2880	ENSPG01343.gene	.	+	BGI	gene	.	ID=ENSPG01343.gene;Accession=GWHGAAFD003259;
GWHAAFD00000025	5988	6690	CDS	.	+	BGI	CDS	0	ID=CDS;Parent=ENSPG05616;Parent_Accession=GWHTAAFD004225;Protein_Accession=GWHPAAFD004225;
GWHAAFD00000025	5988	6690	ENSPG05616	.	+	BGI	mRNA	.	ID=ENSPG05616;Accession=GWHTAAFD004225;Parent=ENSPG05616.gene;Parent_Accession=GWHGAAFD004225;
GWHAAFD00000025	5988	6690	ENSPG05616.gene	.	+	BGI	gene	.	ID=ENSPG05616.gene;Accession=GWHGAAFD004225;
GWHAAFD00000025	7450	8734	CDS	.	+	BGI	CDS	0	ID=CDS;Parent=ENSPG05617;Parent_Accession=GWHTAAFD004226;Protein_Accession=GWHPAAFD004226;
GWHAAFD00000025	7450	8734	ENSPG05617	.	+	BGI	mRNA	.	ID=ENSPG05617;Accession=GWHTAAFD004226;Parent=ENSPG05617.gene;Parent_Accession=GWHGAAFD004226;
GWHAAFD00000025	7450	8734	ENSPG05617.gene	.	+	BGI	gene	.	ID=ENSPG05617.gene;Accession=GWHGAAFD004226;
GWHAAFD00000043	5294	6469	CDS	.	-	BGI	CDS	2	ID=CDS;Parent=ENSPG12152;Parent_Accession=GWHTAAFD004816;Protein_Accession=GWHPAAFD004816;
GWHAAFD00000043	5294	19524	ENSPG12152	.	-	BGI	mRNA	.	ID=ENSPG12152;Accession=GWHTAAFD004816;Parent=ENSPG12152.gene;Parent_Accession=GWHGAAFD004816;
```

**Comment by nextgenusfs** [comment]
Hi @simone-says.  That format is not GFF3. It looks like BED format with some additional columns.

**Comment by simone-says** [comment]
Whoops sorry that was from the BED file version, I've only been using GFF3 annotation files. Here is an example from the GFF version:
```
GWHAAFD00004910	BGI	gene	3633344	3645053	.	+	.	ID=ENSPG10139.gene;Accession=GWHGAAFD000039;
GWHAAFD00004910	BGI	mRNA	3633344	3645053	.	+	.	ID=ENSPG10139;Accession=GWHTAAFD000039;Parent=ENSPG10139.gene;Parent_Accession=GWHGAAFD000039;
GWHAAFD00004910	BGI	CDS	3633344	3634124	.	+	0	ID=CDS;Parent=ENSPG10139;Parent_Accession=GWHTAAFD000039;Protein_Accession=GWHPAAFD000039;
GWHAAFD00004910	BGI	CDS	3635297	3635467	.	+	2	ID=CDS;Parent=ENSPG10139;Parent_Accession=GWHTAAFD000039;Protein_Accession=GWHPAAFD000039;
GWHAAFD00004910	BGI	CDS	3637232	3637365	.	+	2	ID=CDS;Parent=ENSPG10139;Parent_Accession=GWHTAAFD000039;Protein_Accession=GWHPAAFD000039;
GWHAAFD00004910	BGI	CDS	3638440	3638560	.	+	0	ID=CDS;Parent=ENSPG10139;Parent_Accession=GWHTAAFD000039;Protein_Accession=GWHPAAFD000039;
GWHAAFD00004910	BGI	CDS	3639313	3639462	.	+	2	ID=CDS;Parent=ENSPG10139;Parent_Accession=GWHTAAFD000039;Protein_Accession=GWHPAAFD000039;
GWHAAFD00004910	BGI	CDS	3640616	3640776	.	+	2	ID=CDS;Parent=ENSPG10139;Parent_Accession=GWHTAAFD000039;Protein_Accession=GWHPAAFD000039;
GWHAAFD00004910	BGI	CDS	3640881	3641063	.	+	0	ID=CDS;Parent=ENSPG10139;Parent_Accession=GWHTAAFD000039;Protein_Accession=GWHPAAFD000039;
```

**Comment by nextgenusfs** [comment]
There are no exons, thus its malformed for eukaryotic GFF3 file.  Is this a prokaryote, I'm thinking not as they don't use `mRNA` features.  You can try to run it through `gfftk sanitize`

**Comment by nextgenusfs** [comment]
And I think you can add --debug to have it print the parsing errors to stderr.

**Comment by simone-says** [comment]
Running with --debug added, I see that the program has issues with the seq IDs as a suspected. Is there a way to change the format to make it compatible? My annotation files all have exons annotated, they are vertebrate genomes not prokaryotes. Here is the error message:
```
Found 1472031 errors in contig_name: showing 10 randomly generated lines/records
GWHBWDU00000001	Liftoff	CDS	255012812	255013082	.	+	.	ID=cds-XP_039208261.1;Parent=rna-XM_039352327.1;Dbxref=GeneID:120312081,Genbank:XP_039208261.1;Name=XP_039208261.1;gbkey=CDS;gene=BIRC6;product=baculoviral IAP repeat-containing protein 6 isoform X3;protein_id=XP_039208261.1;extra_copy_number=0
GWHBWDU00000009	Liftoff	CDS	14801066	14801208	.	+	.	ID=cds-XP_039216804.1;Parent=rna-XM_039360870.1;Dbxref=GeneID:120315866,Genbank:XP_039216804.1;Name=XP_039216804.1;gbkey=CDS;gene=SCMH1;product=polycomb protein SCMH1 isoform X1;protein_id=XP_039216804.1;extra_copy_number=0
GWHBWDU00000002	Liftoff	CDS	127879242	127879323	.	-	.	ID=cds-XP_039186532.1;Parent=rna-XM_039330598.1;Dbxref=GeneID:120302361,Genbank:XP_039186532.1;Name=XP_039186532.1;gbkey=CDS;gene=CCNT1;product=cyclin-T1;protein_id=XP_039186532.1;extra_copy_number=0
GWHBWDU00000003	Liftoff	CDS	64195431	64195445	.	+	.	ID=cds-XP_039176988.1;Parent=rna-XM_039321054.1;Dbxref=GeneID:120297892,Genbank:XP_039176988.1;Name=XP_039176988.1;gbkey=CDS;gene=ADGRL2;product=adhesion G protein-coupled receptor L2 isoform X10;protein_id=XP_039176988.1;extra_copy_number=0
GWHBWDU00000002	Liftoff	exon	63514422	63514522	.	-	.	ID=exon-XM_039334107.1-5;Parent=rna-XM_039334107.1;Dbxref=GeneID:120304023,Genbank:XM_039334107.1;gbkey=mRNA;gene=RMND5B;product=required for meiotic nuclear division 5 homolog B%2C transcript variant X2;transcript_id=XM_039334107.1;extra_copy_number=0
```

**Comment by nextgenusfs** [comment]
I don't think this error here is the cause, I need to look at the code but probably a "warning" is more likely for contig_name having too many characters. So if the GFF files where proteins are missing causing errors is from Liftoff its probably some incomplete gene models?  I don't know from just looking at this. If you want to share the files I can look at it.

**Comment by simone-says** [comment]
[laudakiaSacra.faa.gz](https://github.com/nextgenusfs/gfftk/files/13553416/laudakiaSacra.faa.gz)
[achalinusJinggangensis.faa.gz](https://github.com/nextgenusfs/gfftk/files/13553418/achalinusJinggangensis.faa.gz)

Not all of them are from Liftoff that are giving errors.

**Comment by simone-says** [comment]
[achalinusJinggangensis_filtered.gff.gz](https://github.com/nextgenusfs/gfftk/files/13553431/achalinusJinggangensis_filtered.gff.gz)
[phrynocephalusPrzewalskii_filtered.gff.gz](https://github.com/nextgenusfs/gfftk/files/13553433/phrynocephalusPrzewalskii_filtered.gff.gz)
Most of them are not liftoff annotations that are giving errors. The rest of my liftoff annotation files worked.

**Comment by nextgenusfs** [comment]
Do you have the genomes or at least a subset of the genome that is causing the errors?

**Comment by nextgenusfs** [comment]
What would help me is to share an example single example (genome and GFF3 files or a minimal reproducible example files) and then the command you used.

**Comment by simone-says** [comment]
[phrynocephalusPrzewalskii.genome.sample.fa.gz](https://github.com/nextgenusfs/gfftk/files/13573016/phrynocephalusPrzewalskii.genome.sample.fa.gz)
[achalinusJinggangensis.genome.sample.fa.gz](https://github.com/nextgenusfs/gfftk/files/13573018/achalinusJinggangensis.genome.sample.fa.gz)
Here's the first ~250 seqs for the corresponding genomes to the annotation files. The command I ran was e.g.: 
```
gfftk convert --input-format gff3 --output-format proteins \
-i "achalinusJinggangensis_filtered.gff" \
-f "achalinusJinggangensis.genome.fa" \
-o "achalinusJinggangensis.faa" --debug
```

**Comment by nextgenusfs** [comment]
Oh, I see the problem.  You have tab [\t] whitespace characters in your fasta headers. I guess I had not anticipated this, its not a typical fasta header..... Currently it splits on the first space but not tabs, so I'll update to fix that so it will spit on any whitespace. But you can fix by cleaning up your fasta headers... ie could replace tabs with spaces and it should work
```
sed 's,\t, ,\g' achalinusJinggangensis.genome.fa > test.fa
```
And then they will be parsed properly....
```
>>> from gfftk.fasta import fasta2headers
>>> fasta2headers('achalinusJinggangensis.genome.sample.fa')
{'GWHBWDV00000001\tChromosome'}
>>> fasta2headers('test.fa')
{'GWHBWDV00000001'}
```

**Comment by nextgenusfs** [comment]
Hopefully latest release should solve this, upgrade with pip, ie `python -m pip install -U gfftk`

**Comment by simone-says** [comment]
It's working now thank you! Also, if anyone is interested I added exon annotations to 2 of my annotation files using AGAT's Perl script [https://agat.readthedocs.io/en/latest/tools/agat_convert_sp_gxf2gxf.html](url)
