### ISSUE TITLE
single_exon_transcript same as number of genes

### ISSUE THREAD

**Issue by olekto** [nextgenusfs/gfftk#5]
Hi,
I wonder if there is a bug in how you calculate the number of single_exon_transcripts (or maybe I misunderstood the metric or the code). I get the same number of single_exon_transcript as the number of genes, and I expected these to be different as I get 23625 multiple_exon_transcripts. As I get 37998 genes, shouldn't single_exon_transcript be 37988-23625 = 14363?

Would you consider adding the statistics as recommended here: https://www.earthbiogenome.org/report-on-annotation-standards? In addition to what you have included, that would mean including "average number of transcript per gene, average transcript length, average number exons per gene, average number of CDS exons and CDS length (where applicable)."

It would also be nice to have the relationship mono-exon genes to multi-exon genes, the median number of exons per gene and the maximum number of exons (I think all of these also have been suggested as metrics to be reported for annotations for EBP, or maybe just BGE/ERGA).

Otherwise, it will be really nice to have an alternative to EvindenceModeler. 

Thank you.

Ole

**Comment by nextgenusfs** [comment]
Certainly possible there is a bug, the relevent code is here: https://github.com/nextgenusfs/gfftk/blob/main/gfftk/stats.py#L105-L119. This should be parsing the internal annotation dictionary and effectively be just an either/or -- unless it is erroring for some other reason than the exception.  Do you have a toy dataset that replicates the problem? Maybe just a subset of your total annotation I can run it on?

**Comment by nextgenusfs** [comment]
No need for a test set, I'm getting same result. Let me try to fix.

**Comment by nextgenusfs** [comment]
You can give it a try installing with pip from test-pypi:
```
python -m pip install -i https://test.pypi.org/simple/ gfftk
```

**Comment by olekto** [comment]
Thank you, it works now!

And thank you for implementing that other statistics also.

Ole
