### ISSUE TITLE
Repeats is a list and not a single path or string

### ISSUE THREAD

**Issue by olekto** [nextgenusfs/gfftk#7]
Thank you again for this. I am testing the consensus module now as I hope I can drop it in as a replacement for EVM.

I ran into one issue though, in that it seems repeats are captured as a list:
https://github.com/nextgenusfs/gfftk/blob/main/gfftk/__main__.py#L125

But then is treated like a single value (string or path or whatever:
https://github.com/nextgenusfs/gfftk/blob/main/gfftk/consensus.py#L259

I am not sure what the best way to fix this is. You can't sum the repeats from multiple repeat annotations, since that might exceed the total length of the genome. So I guess you would need to either create a consensus or collapse the repeats, or only accept one argument here. 

Thank you.

Ole

**Comment by nextgenusfs** [comment]
Should probably just be a single file, so just need to remove the maths="+" in the argparse section. I need to check what I'm doing in funannotate2 when calling this, I'm not using the cli but importing as a module.

**Comment by olekto** [comment]
Thank you for answering.

I did pass it only one bed file, but I think that is embedded in a list, so
a list with only one item. Like this:
repeats=['SUPER_12/SUPER_12.repeat.bed']. It does not look like isfile
accepts that: https://www.geeksforgeeks.org/python-os-path-isfile-method/

Ole

**Comment by nextgenusfs** [comment]
okay, its updated on testpypi -- see if that works.

**Comment by olekto** [comment]
I am testing now, but hit an error:
If you change this line:
https://github.com/nextgenusfs/gfftk/blob/480a7c9c74873f081edc09ec4d5d62745f7e0d88/gfftk/consensus.py#L27
to
        [args.fasta] + args.genes + args.proteins + args.transcripts + [args.repeats]
that should work at least I think. It runs with that change.

This was the error I got:
```
  File "/cluster/projects/nn8013k/programs/miniconda3/envs/gfftk/lib/python3.12/site-packages/gfftk/consensus.py", line 27, in consensus
    [args.fasta] + args.genes + args.proteins + args.transcripts + args.repeats
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: can only concatenate list (not "str") to list
```

**Comment by olekto** [comment]
Super! Thank you. Works now.
